#!/bin/bash

echo "=== 创建简化部署版本 ==="
echo ""
echo "问题：依赖安装失败"
echo "解决方案："
echo ""
echo "1. 在Netlify中直接使用以下命令："
echo "   npm install --legacy-peer-deps --force"
echo "   npm run build"
echo ""
echo "2. 环境变量设置："
echo "   NODE_VERSION = 18"
echo "   NPM_FLAGS = --legacy-peer-deps"
echo ""
echo "3. 如果还是失败，可以："
echo "   a. 使用临时链接：https://enchanting-unicorn-ec530b.netlify.app/"
echo "   b. 或者创建一个无依赖版本"
echo ""
echo "请先尝试修改Netlify构建设置！"